version: '3.8'

services:
  servico-pedidos:
    build: ./services/pedidos
    ports:
      - "5000:5000"
    depends_on:
      - servico-estoque

  servico-estoque:
    build: ./services/estoque
    ports:
      - "5001:5001"
